name: Allowlist Request
description: Submit a request to allow a blocked domain/s or sub-domain/s
labels: ["allowlist-request"]
assignees: 
  - systemjargon
body:
  - type: dropdown
    id: blocklists
    attributes:
      label: Which blocklist are you using from this repo?
      multiple: true
      options:
        - Ads
        - Core
        - Core Light
        - Core Heavy
        - Firebog Ticklist
        - HostsVN
        - No Social Media
        - NRD 30 days
        - Porn
        - Restrict-ByPass
        - Telemetry
        - Threats
    validations:
      required: true

  - type: textarea
    id: domains
    attributes:
      label: Specify the domain/s or sub-domain/s to allow
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: Why should the domain/s or sub-domain/s be allowed?
      description: |
        What happens if this is not allowed? What functions do not work for a domain or site? 
    validations:
      required: true
