name: Filters Allowlist Compiler

on:
  schedule:
    - cron: '30 1 * * *'

  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '16'  
    - run: npm i -g @adguard/hostlist-compiler

# Lists input and output    
    - name: Compile Allow list
      run: hostlist-compiler -c ./source/allowlist.json -o allowlist.txt

    - name: Start commit change
      run: echo "MSG=Updated at $(date +"%Y%m%d")" >> $GITHUB_ENV
    
    - name: Commit changes
      uses: EndBug/add-and-commit@main
      with:
        default_author: github_actions
        message: ${{ env.MSG }}
