name: SystemJargon Filters - Fix dependancies

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '20.18.0'  
    - run:  npm audit fix --force

    - name: Start commit change
      run: echo "MSG=Updated at $(date +"%Y%m%d")" >> $GITHUB_ENV
    
    - name: Commit changes
      uses: EndBug/add-and-commit@main
      with:
        default_author: github_actions
        message: ${{ env.MSG }}

