name: SystemJargon Filters Compiler

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
#    runs-on: ubuntu-22.04
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '16'  
    - run: npm i -g @adguard/hostlist-compiler

# No longer aggregate bigdargon. Most sites over lap or are designed for Vietnam which are not relevant to me or most.
# Leave as comment incase this changes in the future.
#    - name: Compile bigdargon_HostsVN list
#      run: hostlist-compiler -c ./source/hostsvn.json -o hostsvn.txt

    - name: Compile Security list
      run: hostlist-compiler -c ./source/security.json -o security.txt
      
    - name: Compile Phishing list
      run: hostlist-compiler -c ./source/phishing.json -o phishing.txt
      
    - name: Compile Ads list
      run: hostlist-compiler -c ./source/ads.json -o ads.txt
      
    - name: Compile Core list
      run: hostlist-compiler -c ./source/core.json -o core.txt
    
    - name: Compile Porn list
      run: hostlist-compiler -c ./source/porn.json -o porn.txt
      
#    - name: Compile Porn2 list
#      run: hostlist-compiler -c ./source/porn2.json -o porn2.txt
    
    - name: Compile Telemetry list
      run: hostlist-compiler -c ./source/telemetry.json -o telemetry.txt
      
    - name: Compile Firebog Ticklist
      run: hostlist-compiler -c ./source/firebog-ticklist.json -o firebog-ticklist.txt
 
    - name: Compile Threats list
      run: hostlist-compiler -c ./source/threats.json -o threats.txt
      
    - name: Compile Allow list
      run: hostlist-compiler -c ./source/allowlist.json -o allowlist.txt
      
    - name: Compile Restrict-ByPass list
      run: hostlist-compiler -c ./source/restrict-bypass.json -o restrict-bypass.txt
        
    - name: Start commit change
      run: echo "MSG=Update filter list at $(date +"%Y%m%d")" >> $GITHUB_ENV
    
    - name: Commit changes
      uses: EndBug/add-and-commit@main
      with:
        default_author: github_actions
        message: ${{ env.MSG }}
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1
