name: Filter Compiler

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '16'  
    - run: npm i -g @adguard/hostlist-compiler
    
    - name: Compile HostsVN
      run: hostlist-compiler -c ./source/hostsvn.json -o hostsvn.txt

    - name: Compile Security
      run: hostlist-compiler -c ./source/security.json -o security.txt
      
    - name: Compile Other list
      run: hostlist-compiler -c ./source/other.json -o other.txt
    
    - name: Compile Lite list
      run: hostlist-compiler -c ./source/lite.json -o lite.txt
    
    - name: Compile Porn list
      run: hostlist-compiler -c ./source/porn.json -o porn.txt

    - name: Compile Extra list
      run: hostlist-compiler -c ./source/extra.json -o extra.txt
      
    - name: Compile Telemetry list
      run: hostlist-compiler -c ./source/telemetry.json -o telemetry.txt
      
    - name: Compile Firebog Ticklist
      run: hostlist-compiler -c ./source/firebog-ticklist.json -o firebog-ticklist.txt
         
    - name: Start commit change
      run: echo "MSG=Update filter list at $(date +"%Y%m%d")" >> $GITHUB_ENV
    
    - name: Commit changes
      uses: EndBug/add-and-commit@main
      with:
        default_author: github_actions
        message: ${{ env.MSG }}
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1
