name: resolved
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'domain-added-to-list'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue or Request
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: The domains requested have been added the to appropriate list. It will be effective on the next commit and push.
