name: List Entries Stats

on:
  push:
    branches:
      - dev

jobs:
  line-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clean Previous Stats
        run: rm -f list-entries-stats.txt ads_count.txt core_light_count.txt

      - name: Count lines in ads.txt
        run: |
          grep -vE '^[#!]' filters/ads.txt | wc -l > ads_count.txt

      - name: Count lines in core_light.txt
        run: |
          grep -vE '^[#!]' filters/core_light.txt | wc -l > core_light_count.txt

      - name: Create Stats Report
        run: |
          echo "Line Counts:" > list-entries-stats.txt
          echo "Ads: $(cat ads_count.txt)" >> list-entries-stats.txt
          echo "Core Light: $(cat core_light_count.txt)" >> list-entries-stats.txt
          echo "Total: $(($(cat ads_count.txt) + $(cat core_light_count.txt)))" >> list-entries-stats.txt

      - name: Start commit change
        run: echo "MSG=updated stats at $(date +"%Y%m%d")" >> $GITHUB_ENV
      
      - name: Commit changes
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: ${{ env.MSG }}
    
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
